### PR TITLE
Add Post-Commit Workflow: Build & Archive Wheel

### PR DESCRIPTION
**Pull request by radarrager**
[DVO-757  Build & Release Torchsparse Wheel Artifacts](https://zendar.atlassian.net/browse/DVO-774)
A prelude to actually creating releases we can download directly, this at least gives us usable wheel files we can put into manual releases. PDM is used for the build to maintain consistency with other Zendar builds.

### CODE REVIEW

**Comment by ishivvers** [comment]
Nice - I like the move.

One concern: the `cuda` compiler gets involved with this code, so I think it might be the case that we need to compile a different wheel for each nvidia GPU architecture we support and for each CUDA version we support.

The GPU architecture point is a terrible pain, since pretty much all of the GPUs we have on-prem are the same architecture.  But we could test this by spinning up a GCP instance with a totally different architecture (maybe a T4 or an L4), and see if we can build RadarProcessor and pass our test suite w/ the torchsparse wheel as built here.

Does that make sense?  Thoughts on that point?

**Comment by dranjan** [comment]
> One concern: the `cuda` compiler gets involved with this code, so I think it might be the case that we need to compile a different wheel for each nvidia GPU architecture we support and for each CUDA version we support.

I thought the CUDA compiler generated code for all architectures by default.

**Comment by dranjan** [comment]
CuPy for another example doesn't publish a separate wheel for each architecture.

**Comment by ishivvers** [comment]
@dranjan to be honest you probably have a more complete understanding of how the CUDA build really works; the description above was just my interpretation of the behavior we saw last year, but I may have mis-interpreted.

What we saw was that this code would not work if it was compiled in a docker image on one type of GPU, and then run (inside a docker container) against a different type of GPU.
When we've run this in the cloud, we've had to build different docker images for each GPU type we run on.  If we didn't, we would get `CUDA kernel not found` sort of errors when running a docker image that was built against a different GPU than the one it ran on.  We could not build the docker image with our on-premise machines, and then run it against a GCP machine with an nvidia T4 GPU.

So, I don't _really_ understand how that all worked, but I assumed that some GPU-hardware-specific decisions were being made during the compilation :shrug:

**Comment by radarrager** [comment]
It feels like the main compatibility question is: "With which version of CUDA was your Torch compiled?" What's a good procedure for confirming that?

**Comment by ishivvers** [comment]
Yeah - agreed @radarrager that's required to be an exact match.  This code only works if pytorch and torchsparse were compiled with the same version of CUDA.

Right now, we control that by [version-pinning `torch==2.0.0+cu117`](https://github.com/ZendarInc/torchsparse/blob/c395f76263ae5833d0c1dd1af623203deb3322e5/pyproject.toml#L12) - that's explicitly built against `CUDA 11.7`

**Comment by radarrager** [comment]
Looks like it at least works on the CI hardware it was built on, a first step in testing.

**Comment by ishivvers** [comment]
Nice.

Hmm, so, as I see it, the next step is to try and install this wheel into a cloud machine, which has a known-to-be-dissimilar GPU attached.

I'm running a few of those now, for my ongoing training runs, and it looks like [the built wheel from this exercise should be available for me to pull from the NAS](https://github.com/ZendarInc/RadarProcessor/pull/1410/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R76); want me to give it a spin?

What I would do:
- take one of the A100-equipped machines I'm currently running in GCP
- download our `zendar_ansible_base` docker image
- see if I can install the torchsparse wheel into it, [following this pattern](https://github.com/ZendarInc/RadarProcessor/pull/1410/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R76)
- see if I can then build `RadarProcessor` and pass the unit tests


Thoughts?  Is this ready for me to try it out?

------------

Another question: what would the plan be for distributing these wheels?  We need to support installation on-premise, off-premise, and in the cloud.

**Comment by radarrager** [comment]
I was thinking about this - whatever we use, it'll probably call for some kind of access control - either GCP credentials for Google's Artifact Registry or service tokens for a Cloudflare tunnel. What's the process look like for using secrets on the cloud machines?

**Comment by radarrager** [comment]
The wheel file is ready for trying this out on the A100, but the `pyproject.toml` would need to be altered in RadarProcessor to point to wherever the wheelfile is accessible over there. Also, you'd have to shuttle the wheel over, yourself, for now.

**Comment by ishivvers** [comment]
Yep - that all makes sense.  Ok I'll try and run that exercise in the next day or two, and will report back here.

**Comment by ishivvers** [comment]
Ok, I've tested [the wheel from here](https://github.com/ZendarInc/RadarProcessor/pull/1410/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R76) on both [a GCP T4 machine, and an A100 machine](https://cloud.google.com/compute/docs/gpus), both of which had given us trouble last year with cuda kernal complaints when we tried to build `torchsparse` on one and run it on the other.

Installation with the wheel worked just fine, in both cases :tada: :tada: 
I was able to install, build RadarProcessor, pass unit tests, and run data through `lidar_semseg`

So, this effort gets the :green_apple: from me.  Let's see if we can come up with a sane way to share the wheel for both on and off-prem installs, and then roll it out!  It will definitely be a faster / more streamlined installation process.

**Comment by radarrager** [comment]
Great - merging this to get it saved and thinking now on what delivery looks like

**Pull request merged**
